Thread Reader 1 locked record 13 for read
Thread Reader 0 locked record 2 for read
Thread Reader 1 locked record 14 for read
Thread Reader 0 locked record 3 for read
Thread Reader 1 locked record 15 for read
Thread Reader 0 locked record 4 for read
Thread Reader 1 locked record 16 for read
Thread Reader 0 locked record 5 for read
Thread Reader 1 locked record 17 for read
Thread Reader 0 locked record 6 for read
Thread Reader 1 locked record 18 for read
Thread Reader 0 locked record 7 for read
Thread Reader 1 locked record 19 for read
Thread Reader 0 locked record 8 for read
Thread Reader 1 locked record 0 for read
Thread Reader 0 locked record 9 for read
Thread Reader 1 locked record 1 for read
Thread Reader 0 locked record 10 for read
Thread Reader 1 locked record 2 for read
Thread Reader 0 locked record 11 for read
Thread Reader 1 locked record 3 for read
Thread Reader 0 locked record 12 for read
Thread Reader 1 locked record 4 for read
Thread Reader 0 locked record 13 for read
Thread Reader 1 locked record 5 for read
Thread Reader 0 locked record 14 for read
Thread Reader 1 locked record 6 for read
Thread Reader 0 locked record 15 for read
Thread Reader 1 locked record 7 for read
Thread Reader 0 locked record 16 for read
Thread Reader 1 locked record 8 for read
Thread Reader 0 locked record 17 for read
Thread Reader 1 locked record 9 for read
Thread Reader 0 locked record 18 for read
Thread Reader 1 locked record 10 for read
Thread Reader 0 locked record 19 for read
Thread Reader 1 locked record 11 for read
Thread Reader 0 locked record 0 for read
Thread Reader 1 locked record 12 for read
Thread Reader 0 locked record 1 for read
Thread Reader 1 read 13 value = null
Thread Reader 0 read 2 value = null
Thread Reader 1 read 14 value = null
Thread Reader 0 read 3 value = null
Thread Reader 1 read 15 value = null
Thread Reader 0 read 4 value = null
Thread Reader 1 read 16 value = null
Thread Reader 0 read 5 value = null
Thread Reader 1 read 17 value = null
Thread Reader 0 read 6 value = null
Thread Reader 1 read 18 value = null
Thread Reader 0 read 7 value = null
Thread Reader 1 read 19 value = null
Thread Reader 0 read 8 value = null
Thread Reader 1 read 0 value = null
Thread Reader 0 read 9 value = null
Thread Reader 1 read 1 value = null
Thread Reader 0 read 10 value = null
Thread Reader 1 read 2 value = null
Thread Reader 0 read 11 value = null
Thread Reader 1 read 3 value = null
Thread Reader 0 read 12 value = null
Thread Reader 1 read 4 value = null
Thread Reader 0 read 13 value = null
Thread Reader 1 read 5 value = null
Thread Reader 0 read 14 value = null
Thread Reader 1 read 6 value = null
Thread Reader 0 read 15 value = null
Thread Reader 1 read 7 value = null
Thread Reader 0 read 16 value = null
Thread Reader 1 read 8 value = null
Thread Reader 0 read 17 value = null
Thread Reader 1 read 9 value = null
Thread Reader 0 read 18 value = null
Thread Reader 1 read 10 value = null
Thread Reader 0 read 19 value = null
Thread Reader 1 read 11 value = null
Thread Reader 0 read 0 value = null
Thread Reader 1 read 12 value = null
Thread Reader 1 released record 13 for read
Thread Reader 1 released record 14 for read
Thread Reader 1 released record 15 for read
Thread Reader 1 released record 16 for read
Thread Reader 1 released record 17 for read
Thread Reader 1 released record 18 for read
Thread Reader 1 released record 19 for read
Thread Reader 1 released record 0 for read
Thread Reader 1 released record 1 for read
Thread Reader 1 released record 2 for read
Thread Reader 1 released record 3 for read
Thread Reader 1 released record 4 for read
Thread Reader 1 released record 5 for read
Thread Reader 1 released record 6 for read
Thread Reader 1 released record 7 for read
Thread Reader 1 released record 8 for read
Thread Reader 1 released record 9 for read
Thread Reader 1 released record 10 for read
Thread Reader 1 released record 11 for read
Thread Reader 1 released record 12 for read
Thread Reader 0 read 1 value = null
Thread Reader 0 released record 2 for read
Thread Reader 0 released record 3 for read
Thread Reader 1 locked record 5 for read
Thread Reader 0 released record 4 for read
Thread Reader 1 locked record 6 for read
Thread Reader 0 released record 5 for read
Thread Reader 1 locked record 7 for read
Thread Reader 0 released record 6 for read
Thread Reader 1 locked record 8 for read
Thread Reader 0 released record 7 for read
Thread Reader 1 locked record 9 for read
Thread Reader 0 released record 8 for read
Thread Reader 1 locked record 10 for read
Thread Reader 0 released record 9 for read
Thread Reader 1 locked record 11 for read
Thread Reader 0 released record 10 for read
Thread Reader 1 locked record 12 for read
Thread Reader 0 released record 11 for read
Thread Reader 1 locked record 13 for read
Thread Reader 0 released record 12 for read
Thread Reader 1 locked record 14 for read
Thread Reader 0 released record 13 for read
Thread Reader 1 locked record 15 for read
Thread Reader 0 released record 14 for read
Thread Reader 1 locked record 16 for read
Thread Reader 0 released record 15 for read
Thread Reader 1 locked record 17 for read
Thread Reader 0 released record 16 for read
Thread Reader 1 locked record 18 for read
Thread Reader 0 released record 17 for read
Thread Reader 1 locked record 19 for read
Thread Reader 0 released record 18 for read
Thread Reader 1 locked record 0 for read
Thread Reader 0 released record 19 for read
Thread Reader 1 locked record 1 for read
Thread Reader 0 released record 0 for read
Thread Reader 1 locked record 2 for read
Thread Reader 0 released record 1 for read
Thread Reader 1 locked record 3 for read
Thread Reader 1 locked record 4 for read
Thread Reader 0 locked record 1 for read
Thread Reader 0 locked record 2 for read
Thread Reader 0 locked record 3 for read
Thread Reader 0 locked record 4 for read
Thread Reader 0 locked record 5 for read
Thread Reader 0 locked record 6 for read
Thread Reader 0 locked record 7 for read
Thread Reader 0 locked record 8 for read
Thread Reader 0 locked record 9 for read
Thread Reader 0 locked record 10 for read
Thread Reader 0 locked record 11 for read
Thread Reader 0 locked record 12 for read
Thread Reader 0 locked record 13 for read
Thread Reader 0 locked record 14 for read
Thread Reader 0 locked record 15 for read
Thread Reader 0 locked record 16 for read
Thread Reader 0 locked record 17 for read
Thread Reader 0 locked record 18 for read
Thread Reader 0 locked record 19 for read
Thread Reader 0 locked record 0 for read
Thread Reader 1 read 5 value = null
Thread Reader 0 read 1 value = null
Thread Reader 1 read 6 value = null
Thread Reader 0 read 2 value = null
Thread Reader 1 read 7 value = null
Thread Reader 0 read 3 value = null
Thread Reader 1 read 8 value = null
Thread Reader 0 read 4 value = null
Thread Reader 1 read 9 value = null
Thread Reader 0 read 5 value = null
Thread Reader 1 read 10 value = null
Thread Reader 0 read 6 value = null
Thread Reader 1 read 11 value = null
Thread Reader 0 read 7 value = null
Thread Reader 1 read 12 value = null
Thread Reader 0 read 8 value = null
Thread Reader 1 read 13 value = null
Thread Reader 0 read 9 value = null
Thread Reader 1 read 14 value = null
Thread Reader 0 read 10 value = null
Thread Reader 1 read 15 value = null
Thread Reader 0 read 11 value = null
Thread Reader 1 read 16 value = null
Thread Reader 0 read 12 value = null
Thread Reader 1 read 17 value = null
Thread Reader 0 read 13 value = null
Thread Reader 1 read 18 value = null
Thread Reader 0 read 14 value = null
Thread Reader 1 read 19 value = null
Thread Reader 0 read 15 value = null
Thread Reader 1 read 0 value = null
Thread Reader 0 read 16 value = null
Thread Reader 1 read 1 value = null
Thread Reader 0 read 17 value = null
Thread Reader 1 read 2 value = null
Thread Reader 0 read 18 value = null
Thread Reader 1 read 3 value = null
Thread Reader 0 read 19 value = null
Thread Reader 1 read 4 value = null
Thread Reader 1 released record 5 for read
Thread Reader 1 released record 6 for read
Thread Reader 1 released record 7 for read
Thread Reader 0 read 0 value = null
Thread Reader 1 released record 8 for read
Thread Reader 0 released record 1 for read
Thread Reader 1 released record 9 for read
Thread Reader 0 released record 2 for read
Thread Reader 1 released record 10 for read
Thread Reader 0 released record 3 for read
Thread Reader 1 released record 11 for read
Thread Reader 0 released record 4 for read
Thread Reader 1 released record 12 for read
Thread Reader 0 released record 5 for read
Thread Reader 1 released record 13 for read
Thread Reader 0 released record 6 for read
Thread Reader 1 released record 14 for read
Thread Reader 0 released record 7 for read
Thread Reader 1 released record 15 for read
Thread Reader 0 released record 8 for read
Thread Reader 1 released record 16 for read
Thread Reader 0 released record 9 for read
Thread Reader 1 released record 17 for read
Thread Reader 0 released record 10 for read
Thread Reader 1 released record 18 for read
Thread Reader 0 released record 11 for read
Thread Reader 1 released record 19 for read
Thread Reader 0 released record 12 for read
Thread Reader 1 released record 0 for read
Thread Reader 0 released record 13 for read
Thread Reader 1 released record 1 for read
Thread Reader 0 released record 14 for read
Thread Reader 1 released record 2 for read
Thread Reader 0 released record 15 for read
Thread Reader 1 released record 3 for read
Thread Reader 0 released record 16 for read
Thread Reader 1 released record 4 for read
Thread Reader 0 released record 17 for read
Thread Reader 0 released record 18 for read
Thread Writer 1 locked recored 13 for write
Thread Writer 0 locked recored 1 for write
Thread Writer 1 locked recored 14 for write
Thread Writer 0 locked recored 2 for write
Thread Writer 1 locked recored 15 for write
Thread Writer 0 locked recored 3 for write
Thread Writer 1 locked recored 16 for write
Thread Writer 0 locked recored 4 for write
Thread Writer 1 locked recored 17 for write
Thread Reader 0 released record 19 for read
Thread Writer 1 locked recored 18 for write
Thread Reader 0 released record 0 for read
Thread Reader 1 locked record 5 for read
Thread Writer 1 locked recored 19 for write
Thread Reader 0 locked record 8 for read
Thread Reader 1 locked record 6 for read
Thread Writer 1 locked recored 0 for write
Thread Reader 0 locked record 9 for read
Thread Reader 1 locked record 7 for read
Thread Reader 0 locked record 10 for read
Thread Reader 1 locked record 8 for read
Thread Reader 0 locked record 11 for read
Thread Reader 1 locked record 9 for read
Thread Reader 0 locked record 12 for read
Thread Reader 1 locked record 10 for read
Thread Reader 1 locked record 11 for read
Thread Reader 1 locked record 12 for read
Thread Reader 0 interrupted
Thread Reader 1 interrupted
Thread Writer 0 interrupted
Thread Writer 1 interrupted
ReaderWriter: interrupted
